doc/reference/operators/contents.rst, doc/reference/operators/hamiltonians.rst, doc/reference/operators/operators.rst
Far from perfect, but must be enough to start using `many_body_operator` in a new TRIQS application.
`doc/reference/operators/hamiltonians.rst` is empty for the time being. It should be filled with a useful description of `pytriqs.operators.hamiltonians`.
=> [doc] Minimal docs for many_body_operator

triqs/hilbert_space/state.hpp
* A workaround for a bug in Clang 3.4 was itself buggy.
* Need this fix urgently for the state classification functionality in cthyb.
=> [hilbert_space] Fix for function project(state,hilbert_space)

doc/reference/operators/util.rst, pytriqs/operators/util/CMakeLists.txt, pytriqs/operators/util/__init__.py, pytriqs/operators/util/observables.py
@pseth: Hi Pri, you should be able to merge this one, right?
* Operator presets for some widely used observables: `N_total`, `S_{x,y,z,+,-}`, `S^2`, `L_{x,y,z,+,-}`, `L^2`, `L*S`.
* Fully customizable through spin_names, orb_names, offdiag, map_operator_structure and basis transformation matrices.
* All functions are documented.
=> [op_utils] New pytriqs module pytriqs.operators.util.observables

pytriqs/c++2py/mako/xxx_desc.py, test/pytriqs/wrap_test/a.hpp, test/pytriqs/wrap_test/my_module_desc.py, test/pytriqs/wrap_test/wrap_a.output, test/pytriqs/wrap_test/wrap_a.py, triqs/python_tools/converters/tuple.hpp
* Converts any Python sequence of length N>=0 to std::tuple<...> with the same number of elements.
* Converts std::tuple<...> to a Python list.
* No bits of Boost are used, only the standard C++11 library.
* Wrapping test is updated.
=> [c++2py] New converter for std::tuple.

pytriqs/c++2py/mako/parameters.rst
With this patch one can use two special tags 'type:' and 'default:' when documenting a member of the parameter class. For example,
```c++
/// Quantum numbers
/// type: list(Operator)
/// default: []
std::vector<real_operator_t> quantum_numbers = std::vector<real_operator_t>{};
```
or
```c++
/// Verbosity level
/// default: 3 on MPI rank 0, 0 otherwise.
int verbosity = ((boost::mpi::communicator().rank() == 0) ? 3 : 0); // silence the slave nodes
```
Automatically extracted expressions like `((boost::mpi::communicator().rank() == 0) ? 3 : 0)` may look quite ugly and break formatting of the documentation page.
=> [c++2py] Optionally override 'Type' and 'Default' fields of parameter's doc

triqs/hilbert_space/fundamental_operator_set.hpp, triqs/operators/many_body_operator.hpp
During a recent debugging session I realized that the first (and last) place, where invalid indices of a `many_body_operator` can be detected, is `fundamental_operator_set::operator[]`. This function may throw an instance of `std::out_of_range` with an empty message, which gives no clue about the actual problem.
=> [hilbert_space] Meaningful exception message from fundamental_operator_set::operator[]

cmake/FindCompilerCheck.cmake, cmake/test_clang.cpp, cmake/test_gcc.cpp
Following up with issue #328 I took the post from branch gcc6 and rebased to current master. It includes for GCC the use of the CMAKE_CXX_COMPILER_VERSION
Tested in archlinux with GCC 6.1.1 and cmake 3.5.2
White-space was cleaned in file
=> Compile under GCC6

triqs/python_tools/converters/h5.hpp
This fixes the hdf5 1.10.0 compilation error, caused by a library internal change of the type (hid_t) that stores hdf5 ids (from int -> long).
I have grepped for similar problems in `python_tools`:
```
[python_tools] $ egrep -r "id" * | grep int
converters/h5.hpp:  if ((!id_py) || (!PyInt_Check((PyObject *)id_py))) 
RAISE("hd5 : INTERNAL : group id.id is not an int !!");
```
but can not find any more potential occurrence of this problem. Please consider merging.
Best, Hugo
=> [gfs/hdf5] hdf5 id: int -> hid_t (fixes hdf5 1.10 bug #353)

CMakeLists.txt, cmake/FindNFFT.cmake
Nfft should be found by applications that require it, not with triqs.
Adjustments to FindNFFT.cmake:
-check for API change and make it standalone
Install FindNFFT.cmake alongside triqs
=> Remove Find(NFFT) from Triqs CMakeLists.txt and make FindNFFT.cmake standalone

test/triqs/det_manip/det_manip1.cpp, test/triqs/det_manip/det_manipc1.cpp, test/triqs/det_manip/det_manipc2.cpp, triqs/det_manip/det_manip.hpp
-Added reject_last_try() function that resets all pending operations
(i.e. last_try = No_try)
-API Change: Each try has to be either completed or rejected!
(to avoid bugs and for code clarity)
-Adjusted tests accordingly
-Allow for seperate types of x- (row) and y- (column) index!
(e.g. to choose different index types for c and cdagger in QMC)
=> [det_manip]

triqs/gfs/block/block_gf.hxx, triqs/gfs/block/block_gf.mako.hpp
Moved 
```c++
void operator=(mpi_lazy<mpi::tag::reduce, MAKO_GF::const_view_type> l)
``` 
before operator
```c++
template <typename RHS> MAKO_GF& operator=(RHS&& rhs)
```
since 
```c++
my_block2_gf = mpi_reduce( my_block2_gf, comm); 
```
was picking up the wrong one. Further made some block2_gf specifi adjustments.
=>  Important fixes for block2_gf

cmake/FindFFTW.cmake, cmake/FindGSL.cmake, cmake/FindNFFT.cmake, cmake/FindTRIQS.cmake
In the find modules for the c/c++ libraries the common environment
variables should be checked! Compare e.g.
https://gcc.gnu.org/onlinedocs/gcc-6.3.0/gcc/Environment-Variables.html
https://clang.llvm.org/docs/CommandGuide/clang.html#environment
Further, made the order between the header and library searches more
consistent to not accidentally mix headers/libs of two installations.
@mferrero  Do you agree?
=> [cmake] Check common environment in Cmake Find Modules. 

CMakeLists.txt, cmake/has_optional.cpp, triqs/utility/optional_compat.hpp
Commit 90ec42e8a7430beba5161b2acec2f8828fa54826 is too optimistic about compiler's support for `<optional>` header.
Here I check for `<optional>` explicitly.
=> [cmake] Properly check <optional> availability (fix #401)

triqs/operators/many_body_operator.hpp
Added additional constructor to many_body_operator to allow for e.g.
```c++
many_body_operator h_int;
...
many_body_operator h_dens; 
for (auto const &term : h_int)
if ( is_density_interaction(term) ) h_dens = h_int_dens + term;
```
@krivenko What do you think?
Maybe add a check if the monomial is ordered correctly?
=> [many_body_operator]

triqs/gfs/meshes/product.hpp
-added index_t constructor taking tuple of indices
-small bugfix in mesh_point
-added member function 'index' for mesh_point<cartesian_product< ... >> to
be consistent with e.g. mesh_point<gf_mesh<imfreq>>
=> [product-mesh]

triqs/arrays/python/numpy_extractor.hpp
I recompiled my triqs from master and started seeing a lot of deprecation warnings regarding NPY_CHAR. This small patch fixes it.
NPY_CHAR was deprecated in numpy 1.7 but its complete deprecation started
being enforced in numpy 1.13
=> Change NPY_CHAR to NPY_STRING

CMakeLists.txt, cmake/has_optional.cpp
Fixes #462
Relates to #401
We have to check for both, the availability of #include <optional> and
the version of c++ (i.e. -std=c++1y vs c++1z)
=> [optional] Fixes #462

pytriqs/operators/util/U_matrix.py
added the l = 1 case for U_J_to_radial_integrals and radial_integrals_to_U_J according to volga.eng.yale.edu/sites/default/files/files/UJ-form-of-Vee.pdf
=> U_J_to_radial_integrals for l=1

triqs/lattice/brillouin_zone.hpp, triqs/lattice/gf_mesh_cyclic_lattice.hpp
-Construct gf_mesh<cyclic_lattice> from domain and linear cluster mesh size
-Allow cast of brillouin_zone to bravais_lattice
These changes unify the interface of the gf_mesh and allow for a generic
fourier implementation that works for imfreq, imtime, cyclic_lattice,
brillouin_zone
=> [brillouin_zone, gf_mesh] Changes relevant for a generic fourier impl

pytriqs/gf/block_gf.py, pytriqs/gf/tools.py, pytriqs/sumk/sumk_discrete.py
Some cleaning of the `sumk` and `tail_fit` from `g.N1` and `g.N2` usage, now replaced with `g.target_shape[]`.
Please merge.
=> [gf] fix pytriqs g.N1, g.N2 usage

triqs/gfs/block/block_gf.hxx, triqs/gfs/block/block_gf.mako.hpp, triqs/gfs/functions/functions2.hpp, triqs/gfs/gf/gf.hxx, triqs/gfs/gf/gf.mako.hpp, triqs/gfs/gf/targets.hpp, triqs/operators/many_body_operator.hpp, triqs/test_tools/many_body_operator.hpp, triqs/utility/numeric_ops.hpp, triqs/utility/real_or_complex.hpp
**[gf,block_gf]** Added type real_t to gfs and all target types
-gf, block_gf, block2_gf now have an interal real_t that corresponds to
the real version of the Green function type    
-made the is_gf_real function slightly more restrictive
-The different target types that can be used for a gf now all have an
internal real type
-**BugFix**: __make_zero( .. ) in gf needs special behaviour also for scalar_real_valued
**[many_body_operator]** Small fix and operator==
-added == operator for many_body_operator_generic
-normalize_and_insert should take monomial by copy
=> [gf,many_body_operator] Small fixes and additions

test/triqs/utility/tuple_tools.cpp, triqs/utility/tuple_tools.hpp
-Remove zip from std namespace and rename to zip_tuples
-Remove inverse_filter due to lack of use
-Replace map_on_zip by map_on_zip_v2 
-Make map_on_zip and for_each_zip generic
-Further cleaning: Remove use of RETURN macro
=> [tuple_toools] zip->zip_tuples, removed inverse_filter, map_on_zip_v2

triqs/gfs/gf/comma.hpp
Copy-list-initialization of a tuple is forbidden before C++17.
=> [gf] Fix #501

triqs/gfs/singularity/tail.hxx, triqs/gfs/singularity/tail.mako.hpp
To get proper results from tail (and GF) multiplication, NAN from the first
operand should not propagate if the component of second operand vanishes!
@parcollet Please review and merge!
=> [gf/tail] Bugfix: NAN propagation in tail

test/triqs/gfs/functions/real.cpp, triqs/gfs/block/block_gf.hxx, triqs/gfs/block/block_gf.mako.hpp, triqs/gfs/block/map.hpp, triqs/gfs/functions/functions2.hpp, triqs/gfs/functions/imfreq.hpp
-Enabling map_block_gf for block2_gf
-FIX real(Gf) now unsets the tail and keeps indices
-Adding real(block_gf), real(block2_gf) + test
-Add is_gf_real(block_gf), is_gf_real(block2_gf) + test
-Add is_gf_real_in_tau(block_gf), is_gf_real_in_tau(block2_gf) + test
-Add make_gf_real_in_tau(block_gf), make_gf_real_in_tau(block2_gf) + test
@parcollet Please review and merge. In particular check the adjustments in real(Gf) regarding
tail and indices!
=> [gf] Extending block/block2 gf functionality: real, map, ..

pytriqs/gf/backwd_compat/gf_imfreq.py, pytriqs/gf/backwd_compat/gf_imtime.py, pytriqs/gf/backwd_compat/gf_refreq.py, pytriqs/gf/backwd_compat/gf_retime.py, pytriqs/gf/backwd_compat/tool_gfloc.py, pytriqs/gf/descriptor_base.py, pytriqs/gf/singularities_desc.py, pytriqs/gf/tools.py, test/triqs/gfs/fit_tail.cpp, test/triqs/gfs/multivar/g_k_tail.cpp, triqs/arrays/indexmaps/common.hpp, triqs/gfs/functions/legendre.cpp, triqs/gfs/functions/legendre.hpp, triqs/gfs/singularity/fit_tail.cpp, triqs/gfs/singularity/fit_tail.hpp, triqs/gfs/singularity/tail.hxx, triqs/gfs/singularity/tail.mako.hpp, triqs/gfs/transform/fourier_two_variables.cpp, triqs/gfs/transform/legendre_matsubara.cpp
-**Bugfix**: tail.reset(n) now properly resets all moments starting from n to NaN (unknown) 
-adjusting fit_tail and constructors accordingly
-Cleaning of fit_tail.cpp
-Removing all usage of constructor __tail(n1, .. )
-Removing all usage __tail(shape, n_orders, omin)
-Adjusted python tail constructors for backward compatibility
-Added deprecation warnings for improper constructors
-**FIX** by Gernot for complex fitting in one go
-Some cleaning in fit_tail.cpp
=> [tail] Fixing __tail.reset, Complex Fitting in one go

triqs/utility/pade_approximants.hpp
The present Pade code returns NaN when number of Matsubara is large. This pull request fixes this problem. What is changed is that variables A1, A2, B1, B2 are normalized in every step of the iteration so that those do not overflow. It avoids NaN and keeps the ratio A2/B2 (final result).
You can reproduce the above problem using the sample code in
https://triqs.ipht.cnrs.fr/1.x/reference/gfs/py/block/GfReFreq.html
Increase L from 101 to, e.g. 1001, and you will obtain NaN if you print g_pade.data.
In the fixed version, you can obtain correct results for arbitrary number of L.
Best,
Junya Otsuki
=> [pade] Fix a problem that arises for large n_points

cmake/FindSphinx.cmake, doc/sphinxext/autorun/autorun.py, doc/sphinxext/triqs_example/triqs_example.py, test/triqs/gfs/block.cpp, test/triqs/gfs/block2.cpp, triqs/gfs/block/block_gf.hxx, triqs/gfs/block/block_gf.mako.hpp, triqs/gfs/block/expr.hpp, triqs/gfs/block/mapped_functions.hxx, triqs/gfs/block/mapped_functions.mako.hpp, triqs/gfs/gf/gf.hxx, triqs/gfs/gf/gf.mako.hpp
@parcollet Please review changes in mako files below
-The general assignment operator of block2gf was not properly resizing ```_glist``` and ```_blocknames```.
-The general assignment operator of block2gf was preferred over copy assignment operator due to const qualifier
-Some cleaning in gf and blockgf mako file
=> [gf] Fix #541 Fix two bugs in block2_gf copy assignment, some cleaning

ChangeLog.md, pytriqs/operators/util/op_struct.py, test/pytriqs/atom_diag/atom_diag_python.py, test/triqs/atom_diag/atom_diag_complex.cpp, test/triqs/atom_diag/atom_diag_real.cpp, test/triqs/h5/h5_io.cpp, triqs/h5.hpp, triqs/h5/pair.hpp, triqs/hilbert_space/fundamental_operator_set.hpp
- Replace gf_struct_t (was `map<string, vector<variant<int, string>>>`)
by `vector<pair<string, vector<variant<int, string>>>>` in order to
maintain block-order
- Adjust set_operator_structure correspondingly
- Adjust tests
- Add to Changelog
=> [many_body_operator] Replace gf_struct_t by vector<pair<...>> Fix #342

triqs/utility/pade_approximants.hpp
Hi, here is a further improvement from one of our colleagues.
When we continue numerically orbital diagonal data, we may encounter "division by zero".
This patch fixes this problem by truncating the expansion in such cases.
=> Improved pade approximants for numerically orbital diagonal data

doc/reference/statistical_analysis/green_function_0.cpp
Increasing the number of frequencies from 20 to 200 in one example to satisfy error bounds on the tail fit in the fourier transform.
=> [doc] statistics analysis gf tail warning fix

pytriqs/gf/gf.py
Docstrings have to be the first statement after the definition.
=> Move methaclass of `pytriqs.gf.Gf` after docstring

pytriqs/archive/hdf_archive_basic_layer_h5py.py
=> Added missing import of h5py.highlevel

triqs/arrays/storages/mem_block.hpp
Fix to make gf_views thread safe using std::atomic on the reference counters.
=> [array] make ref_counters std::atomic

test/pytriqs/base/CMakeLists.txt, test/pytriqs/base/bug_tight_binding.py
I spent a few hours trying to understand why my dmft loop crashed about 20% of the times the script was run.
It turns out I was passing hopping matrices with incorrect dimensions to `TightBinding` and for some reason it is accepted without any complaints. This causes the lattice Green's function computed by `Sumk` to have uninitialized data, hence the intermittent crashing behavior.
Someone was proactive and added checks for the dimensions on the c++ side but this seems for some reason not be active. 
This pull request is a test that fails when `TightBinding` accepts incorrect hopping dimensions without throwing.
Please merge.
=> Bad bug in TightBinding, checking hopping matrix dims, not active

test/triqs/atom_diag/f_shell.cpp, triqs/atom_diag/atom_diag.hpp, triqs/atom_diag/impl/atom_diag.cpp, triqs/atom_diag/impl/worker.cpp
Dear all,
This fixes the `atom_diag` feature of only considering a restricted range of the total occupation when building the Fock space.
The commit 8b28b5a exposes the interface and adds a test that uses the constrained occupation range constructor. The commit 64ffc6 is a patch from @krivenko that fixes the internal bug in `atom_diag` that caused it to segfault when encountering empty subsectors. With this modification the test passes.
@Wentzell I discussed the test and interface with you before. Here is both that and the required fix to make the test pass. Could you please have a look?
Best regards,
Hugo
=> Total occupation number constraints in atom diag (fix of functionality regression)

pytriqs/gf/descriptors.py
Add `chem_potential` key-word argument to allow SemiCircular density of states away from half-filling.
The argument should be renamed to match TRIQS naming conventions.
The function seems not yet to properly work, as `density()` complains about non-vanishing 0th.
=> Add key-word argument for center of SemiCircular

test/triqs/atom_diag/atom_diag_op_matrix.cpp, triqs/atom_diag/atom_diag.hpp, triqs/atom_diag/impl/atom_diag.cpp
Dear all,
Here is the separated pull request for atomdiag and the new op_block_mat_t for handling the matrix representation of general operators. This is used in cthyb to do sampling by insertion.
Please give feedback on this.
Best, Hugo
=> [atom_diag] block matrix repr for operators

triqs/mc_tools/mc_generic.hpp, triqs/mc_tools/mc_measure_set.hpp
This is a fix for issue #604 making it possible to disable the timers for the mc measures by passing an additional flag in the constructor. As suggested in the triqs meeting discussion Nov 16.
@amoutenet Could you please try this fix and check that it solves your speed issue?
Best, H
=> [mc] make measure timer optional

pytriqs/archive/hdf_archive_basic_layer_h5py.py
`h5py.highlevel` has been deprecated since 2015 (see this [commit](https://github.com/h5py/h5py/commit/cac43fd03bdf45bbe8cd8e7836368868d2f439f7)).
Imports should happen directly from the root package, i.e. `from h5py import File`
This fixes #594
=> Avoid usage of deprecated h5py.highlevel

triqs/gfs/meshes/linear_interpolation.hpp
This is both a FIX to #668 and a Bugfix in the linear interpolation weights for one corner-case.
Issue #668 occurs as for large `n_tau` the rounding error accumulated in
```c++
double del = (x_min - x_max) / (n_tau - 1);
double x_max_new = x_min + del * (n_tau - 1);
```
is large than what we permit [here](https://github.com/TRIQS/triqs/blob/b99a06744eac6a07f7d4fb5015e1ef95cde45f2a/triqs/gfs/meshes/linear_interpolation.hpp#L82). This PR raises this margin significantly from `1e-12 -> 1e-8`.
This PR further fixes an error in the linear interpolation weights for the case where `x` is marginally smaller than `x_min`. [Here](https://github.com/TRIQS/triqs/blob/b99a06744eac6a07f7d4fb5015e1ef95cde45f2a/triqs/gfs/meshes/linear_interpolation.hpp#L91) the weight of the left point (i.e. `1-w`) …
=> Bugfix in linear interpolation, adjust rouding error margin, FIX #668

test/triqs/h5/h5_io.cpp, triqs/h5/vector.cpp
This commit makes
`void h5_write_attribute(hid_t ob, std::string const & name, std::vector<std::vector<std::string>> const & V)`
`void h5_read_attribute(hid_t ob, std::string const & name, std::vector<std::vector<std::string>> & V)`
properly handle corner cases when some of the vectors/strings are empty. `h5_io` test has been extended to cover the changed functions.
=> [h5] Fix issue #675

test/triqs/atom_diag/hamiltonian.hpp, test/triqs/hilbert_space/hilbert_test.cpp, test/triqs/hilbert_space/space_partition.cpp, test/triqs/operators/operator_test.cpp, triqs/cpp2py_converters/fundamental_operator_set.hpp, triqs/hilbert_space/fundamental_operator_set.cpp, triqs/hilbert_space/fundamental_operator_set.hpp, triqs/operators/many_body_operator.cpp, triqs/utility/iterator_facade.hpp, triqs/utility/itertools.hpp
In accordance with the type-change of ```gf_struct_t``` to
```c++
gf_struct_t = vector<pair<int,vector<indices_t>>>
```
that was introduced in a746ba5 this commit adjusts the 
```fundamental_operator_set``` to respect the order of blocks in gf_struct
This PR still contains ***unfixed test failures*** for the atom_diag part of triqs.
@krivenko Could you comment on/review this PR and have a look at the test failures in atom_diag?
=> Adjust fundamental operator set to respect order in gf_struct #342

triqs/utility/macros.hpp
e.g.
REQUIRES (std::is_same_v<T,int>) ...
Because of the , the macro see multiple arguments, which have to be forwarded.
https://godbolt.org/z/R6CACN
=> Make REQUIRE macro variadic

pytriqs/gf/tools.py, test/pytriqs/base/tail_issues.py
As of popular request this PR adds back the `delta(g)` pytriqs functionality after the 2.0 tail adjustments.
This new function is very rigorous in its checks of the tail-fit error and fundamental Green Function properties
* The property `g_ij(iw) = g_ji(iw)*` of the input is explicitly checked
* The underlying tailfit implicitly assumes the above property
* The least squares error of the underlying tailfit is evaluated and a Warning is thrown if it exceeds `1e-5`
=> Fix the delta(g) function in pytriqs.gf.tools after tail adjustments

test/pytriqs/base/CMakeLists.txt, test/pytriqs/base/bug_bcast_mesh.py, triqs/lattice/bravais_lattice.hpp
This is a test for a bug in BZMesh where the dimension turns from 3 to 2 when using bcast on the mesh.
=> [bug] bcast mesh

test/triqs/det_manip/det_manip3.cpp, triqs/det_manip/det_manip.hpp
-det_manip should never explicitly go through a singular matrix
-singular matrices should be SKIPPED OVER by the proper operations,
e.g. try_insert2 instead of 2x (try_insert + complete operation)
-throw exception if we encounter a singular determinant in the
regeneration
-regenerate if determinant is zero in the accessor function
-minor formatting
=> [detmanip] Don't regenerate on singular det, Throw in regeneration
