TRIQS/triqs

triqs/hilbert_space/space_partition.hpp
* New method find_mappings()
* Corrected includes
* Index of a Fock state: int -> uint32_t
* Small fixes for better genericity
=> [hilbert_space] Extension of space_partition

triqs/gfs/local/pade.cpp
Initialization of the resultant GF was done in a wrong place.
=> Fix for issue #215.

doc/reference/determinant_manipulation/behind.rst, doc/tutorials/det_manip/det_manip_tutorial.rst, doc/tutorials/det_manip/det_manip_tutorial_7.cpp, doc/tutorials/det_manip/det_manip_tutorial_8.cpp, test/triqs/mc_tools/different_moves_mc.cpp, triqs/det_manip/det_manip.hpp, triqs/utility/c14.hpp
- Addition of some functions in det_manip to add or remove two lines/col at the end of the matrix
- A tutorial added on the new functions. 
- Variable 'I' in utility/c14.hpp can be in conflict when using complex n -> has been renamed 'I_'. 
- The example different_moves_mc.cpp has been updated and commented.
=> Addition of some functions in det_manip

pytriqs/plot/mpl_interface.py
I include de option to call for a figure number in the oplot interphase.
And automatically remove some whitespace.
=> oplot can select figure number

packaging/os_x/triqs.rb
=> osx packaging update

triqs/det_manip/det_manip.hpp
-Added accessors to internal data:
x_values, y_values, matrix_inverse_values
-Fixed a bug where previously a matrix_view to a temporary was
returned
=> [det_manip]

triqs/gfs/gf/gf.hxx, triqs/gfs/gf/partial_eval.hpp, triqs/h5/optional.hpp, triqs/utility/lazy_bracket.hpp, triqs/utility/optional_compat.hpp, triqs/utility/tuple_tools.hpp
Few fixes for compilation with gcc-7,
Removing the c++17 specific parts, as they are beeing developed in the dev17 branch.
=> Fixed compile problem with gcc-7 / c++17

test/triqs/gfs/multivar/p_gg_new.cpp
Fixed error in p_gg_new. 
Calculation changed to out of ph symmetry. 
Small difference in results remains due to finite summation range.
=>  fix p_gg_new

pytriqs/gf/gf.py, test/pytriqs/gf_multivar/CMakeLists.txt, test/pytriqs/gf_multivar/bracket.py
Found two bugs in the double bracket accessor/slicer and wrote simple test case.
=> [gf] python double bracket bugfixes + test

cmake/FindLibClang.cmake, cmake/FindNFFT.cmake
Search for llvm-4.0 and corresponding executables
Add relevant environment variables in Trial paths
@krivenko Do you agree?
=> Update to FindLibClang.cmake:

cmake/FindLibClang.cmake, triqs/arrays/block_matrix.hpp
[block_matrix] Fixed include bug (gcc 7.1) in block_matrix.hpp
=> [cmake] Added llvm-4.0 directories to FindLibclang.cmake

pytriqs/gf/local/descriptors.py
added "self." to "half_bandwidth"
=> tiny fix in __str__ of Flat

test/triqs/gfs/make_gf.cpp, triqs/arrays/array.hpp, triqs/gfs.hpp, triqs/gfs/gf/gf.hxx, triqs/gfs/gf/gf.mako.hpp, triqs/gfs/make_gf.hpp
-Added target() function that returns struct with shape and Target type (e.g. matrix_valued)
-Minor fixes in the gf data accessors
-Added new make_gf factories that take either
(mesh, target, memory_layout)
(mesh, target)
(gf_or_view, memory_layout)
or
(gf_or_view)
-Added a test using them.
=> [gf] New factory functions for gf

test/triqs/arrays/c_ordered_transposed_view.cpp, test/triqs/arrays/slice_index_order.cpp, test/triqs/gfs/make_gf.cpp, test/triqs/gfs/multivar/g_nu_nup.cpp, triqs/arrays/array.hpp, triqs/arrays/cache.hpp, triqs/arrays/group_indices.hpp, triqs/arrays/impl/indexmap_storage_pair.hpp, triqs/arrays/indexmaps/cuboid/foreach.hpp, triqs/arrays/indexmaps/cuboid/map.hpp, triqs/arrays/indexmaps/cuboid/mem_layout.hpp, triqs/arrays/indexmaps/cuboid/slice.hpp, triqs/arrays/linalg/det_and_inverse.hpp, triqs/arrays/matrix.hpp, triqs/arrays/proxy.hxx, triqs/arrays/vector.hpp, triqs/gfs/block/block_gf.hxx, triqs/gfs/block/functions.hxx, triqs/gfs/block/mapped_functions.hxx, triqs/gfs/gf/gf.hxx, triqs/gfs/gf/gf.mako.hpp, triqs/gfs/make_gf.hpp, triqs/gfs/meshes/multivar_eval.hxx, triqs/gfs/singularity/tail.hxx
-Renamed memory_layout -> memory_layout_t
-Renamed get_memory_layout -> memory_layout
-Added functionality to check weather a memory_layout member function
exists
-Adjusted array to properly copy the memory_layout if e.g. constructed
from an array_view
=> [array] Changed constructor to properly pick up memory_layout from views

test/triqs/gfs/gf_prod.cpp, triqs/gfs/domains/matsubara.hpp
-Implemented product of two matsubara frequencies to yield a complex
-Added a test that calculates and checks the product of two gfs
=> [matsubara] Product of matsubaras, additional gf product test

pytriqs/operators/operators_desc.py, test/pytriqs/base/operator_python_test.py, triqs/operators/many_body_operator.hpp
=> [operator] making many_body_operator_generic comparable in c++,python + test

pytriqs/gf/tools.py
=> [gf] gf/tools.py add missing mesh import

doc/reference/operators/operators.rst, triqs/operators/many_body_operator.hpp
Following suggestion of @francescopt.
https://github.com/TRIQS/triqs/issues/364#issuecomment-260948562
=> [operators] Add friend foreach_monomial()

pytriqs/statistics/histograms_desc.py, test/pytriqs/base/CMakeLists.txt, test/pytriqs/base/histogram_bcast.py, triqs/statistics/histograms.hpp
This adds serialization support for the histogram class so that it can be sent over mpi with a test case. Please consider merging.
=> [histogram] make serializable and add test

pytriqs/gf/block_gf.py, pytriqs/gf/gf.py, test/pytriqs/base/CMakeLists.txt, test/pytriqs/base/gf_base_op.py, test/pytriqs/base/gf_block.py, test/triqs/gfs/block.cpp, triqs/atom_diag/impl/gf.cpp, triqs/gfs/block/block_gf.hxx, triqs/gfs/block/block_gf.mako.hpp, triqs/hilbert_space/fundamental_operator_set.hpp
-Add python constructor BlockGf(mesh=mesh, gf_struct=gf_struct,
target_rank=int)
-Add c++ constructor block_gf<Var, Target=matrix_valued>(mesh,
gf_struct)
-Add tests
-Adjust atom_diag files accordingly
=> [block_gf] Add constructor from mesh and gf_struct for python and c++

test/triqs/mpi/mpi_array.cpp, triqs/arrays/array.hpp, triqs/arrays/impl/common.hpp, triqs/arrays/impl/indexmap_storage_pair.hpp, triqs/arrays/indexmaps/cuboid/mem_layout.hpp, triqs/arrays/matrix.hpp, triqs/arrays/mpi.hpp, triqs/arrays/vector.hpp
Don't know if I chose the right place for that `set_mem_layout_or_check_if_view()`  function...
=> [mpi] Fix #508

triqs/hilbert_space/imperative_operator.hpp, triqs/hilbert_space/space_partition.hpp, triqs/hilbert_space/state.hpp, triqs/operators/many_body_operator.hpp
@francescopt Would this solve your problem?
=> [many_body_operator] Fix #567

pytriqs/gf/meshes_desc.py, pytriqs/lattice/lattice_tools_desc.py
Adding missing wrappers of lattice domains and meshes.
Please merge.
Best, Hugo
=> Dev lattice wrap

test/triqs/arrays/empty_array_loop.cpp, triqs/arrays/indexmaps/cuboid/domain.hpp, triqs/arrays/indexmaps/cuboid/map.hpp
Here is a bug fix for issue #621. Please consider merging. Best, Hugo
=> [array] zero length iterator bugfix

test/triqs/mpi/CMakeLists.txt, test/triqs/mpi/vector_zero_length.cpp
This is a test that reproduces the zero vector issue in issue #638.
=> [test] mpi zero length vector

doc/reference/statistical_analysis/accumulator.rst, test/triqs/statistics/accumulator.cpp, test/triqs/statistics/autocorr.cpp, test/triqs/statistics/jackknife.cpp, test/triqs/statistics/observable.cpp, triqs/statistics/accumulator.hpp, triqs/statistics/jackknife.hpp
Incorporates update and bug-fixes to accumulator class.
=> Updates to Accumulator; Extra Tests

triqs/utility/time_pt.hpp
Adding serialization for time_pt. (Required to be able to broad cast the cthyb solver over mpi in python.)
Please merge
Best, Hugo
=> [util] time_pt h5 serialization

pytriqs/gf/tools.py
Adding some python documentation to the fit_legendre function. Please merge
=> [tools] fit_legendre doc

doc_temp_storage/OLD_REFERENCE/arrays/IO_0.cpp, test/triqs/statistics/accumulator.cpp, test/triqs/statistics/autocorr.cpp, test/triqs/statistics/g_tau_binning_variance.cpp, test/triqs/statistics/jackknife.cpp, test/triqs/statistics/observable.cpp, triqs/statistics/accumulator.hpp
implements changes of mpi / itertools structure on the stat branch
=> [stat] fixes mpi & intertool includes and naming
